---
output: html_document
runtime: shiny
---

## Adding conditionals

These steps should be completed from the previous example:

1. Add an `inputPanel()` function to produce a radio button console. It should have two options: *Hollow* or *Filled* circles, taking the values 16 and 1 respectively.
2. Next, wrap the plotting functions in a `renderPlot({})` function.
3. Call the internal `input` object, which will be produced by the inputPanel() function, to set the appropriate argument in the plot.

Now, add an option to choose the linear model to show, or if one should be shown at all:

1. Add a net UI widget to the `inputPanel()` function allowing the user to choose if a linear model `geom_smooth(method = "lm")` or a LOESS non-parametric smooth `geom_smooth(method = "loess")` should be added. They should also have the possibility to not see any model if they don't want one.
2. Add another UI widget which allows the user to set the `span` argument in the LOESS model. This will range from 0.15 - 1.


```{r}
library(ggplot2)

p <- ggplot(mtcars, aes(mpg, wt)) +
  geom_point(col = "red", alpha = 0.5, size = 3, shape = 19)

p + geom_smooth(method = "lm", se = F) 
```

*`se = F` is set to prevent the 95% interval from being displayed.
